pages:
  stage: deploy
  tags:
    - prod
  script:
    - mkdir -p public
    - cp index.html login.html manage.html view.html app_viewer.js firebase-init.js public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
